---
- name: Install and provide a functional Apache Tomcat Server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install correct Java version - OpenJDK 11 Headless
      apt:
        name: openjdk-11-jre-headless
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.12/bin/apache-tomcat-10.0.12.tar.gz
        checksum: sha512:e084fc0cc243c0a9ac7de85ffd4b96d00b40b5493ed7ef276d91373fe8036bc953406cd3c48db6b5ae116f2af162fd1bfb13ecdddf5d64523fdd69a9463de8a3
        dest: /opt/apache-tomcat-10.0.12.tar.gz

    - name: Extract Tomcat archive
      unarchive:
        src: /opt/apache-tomcat-10.0.12.tar.gz
        dest: /
        remote_src: yes

