---
- name: Install and provide a functional Apache Tomcat Server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install correct Java version - OpenJDK 8 Headless
      apt:
        name: openjdk-8-jre-headless
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz
        checksum: sha512:https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz.sha512
        dest: /opt/apache-tomcat-9.0.55.tar.gz

    - name: Extract Tomcat archive
      unarchive:
        src: /opt/apache-tomcat-9.0.55.tar.gz
        dest: /
        remote_src: yes

