---
- name: Install and provide a functional Apache Tomcat Server
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install correct Java version - OpenJDK 8 Headless
      apt:
        name: openjdk-8-jre-headless
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz
        checksum: sha512:a0c480b8bba09069bda3b57f54e658450a59d799474ad587dead0ffbf5074c16ee3f9f9c13312d0ff3227c7034589dabf25941fbd672838e9baeee9661e024dc
        dest: /opt/apache-tomcat-9.0.55.tar.gz

    - name: Extract Tomcat archive
      unarchive:
        src: /opt/apache-tomcat-9.0.55.tar.gz
        dest: /
        remote_src: yes

